<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CanliSkor.Core\CanliSkor.Core.csproj" />
    <ProjectReference Include="..\CanliSkor.Infrastructure\CanliSkor.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CanliSkor.Api.Tests" />
  </ItemGroup>

</Project>
